# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
workflows:
  version: 2
  build-workflow:
    jobs:
      build:
        docker:
          - image: circleci/openjdk:8-jdk
        working_directory: ~/repo
        filters:
          tags:
            only: /.*/
        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
        steps:
          - checkout
          - run: ./run

